### ISSUE TITLE
Questions about evaluating code

### ISSUE THREAD

**Issue by alkaidzc** [VCIP-RGBD/RGBD-Pretrain#3]
Dear author, hello. While running the evaluation of your pre trained code, the following issue occurred. After searching, I found that it was a call to timm's creat_madel. Do you have this problem during the evaluation? Also, what are the metrics for pretraining your Large model? Can you please provide it? I don't have that many graphics cards, so I want to observe the pretraining results based on the indicators. Looking forward to your reply, thank you!
`Traceback (most recent call last):
File "D:\zc\RGBD-Pretrain-main\validate.py", line 374, in &lt; module&gt;
main()
File "D:\zc\RGBD-Pretrain-main\validate.py", line 361, in main
validate(args)
File "D:\zc\RGBD-Pretrain-main\validate.py", line 144, in validate
model = create_model(
File "D:\Anaconda3\envs\RGBD_Pretrain\lib\site-packages\timm\models\_factory.py", line 113, in create_model
raise RuntimeError('Unknown model (%s)' % model_name)
RuntimeError: Unknown model (DFormer_Large)
`

**Comment by yinbow** [comment]
This issue not appears on my device (3090 and ubuntu). Your device did not recognize the local models. It may be caused by the system difference between the Linux and Window. On your device, it only support the offical models in TIMM. You need to let the device recognize the local models.
